version: '3.8'

services:
  backend:
    build: ./backend
    container_name: pharmacy-backend
    restart: always
    environment:
      DB_HOST: ep-patient-butterfly-b1bs8i0v-pooler.c-5.eu-central-1.aws.neon.tech
      DB_PORT: 5432
      DB_NAME: neondb
      DB_USER: neondb_owner
      DB_PASSWORD: npg_DGNE8HOfcJi0
    ports:
      - "8080:8080"