global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pharmacy-backend'
    scrape_interval: 30s
    scheme: https
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pharmacy-backend-h2ep.onrender.com']
